///***Supabase Table Definition***
///
/// ```sql
/// create table
/// public."Galaxy_Clusters" (
///   "Galaxy Cluster Name" text null,
///   "Number of Galaxies" text null,
///   "Total Mass (Solar Masses)" text null,
///   "Distance from Earth (million light years)" text null,
///   "Notable Member Galaxies" text null,
///   "Discovery Year" text null,
///   id bigint generated by default as identity not null,
///   constraint Galaxy_Clusters_pkey primary key (id),
///   constraint Galaxy_Clusters_id_key unique (id)
/// ) tablespace pg_default;
/// ```
class GalaxyCluster {
  final int? id;
  final String? galaxyClusterName;
  final String? numberOfGalaxies;
  final String? totalMass;
  final String? distanceFromEarth;
  final String? notableMemberGalaxies;
  final String? discoveryYear;

  GalaxyCluster({
    this.id,
    this.galaxyClusterName,
    this.numberOfGalaxies,
    this.totalMass,
    this.distanceFromEarth,
    this.notableMemberGalaxies,
    this.discoveryYear,
  });

  factory GalaxyCluster.fromJson(Map<String, dynamic> json) {
    return GalaxyCluster(
      id: json['id'],
      galaxyClusterName: json['Galaxy Cluster Name'],
      numberOfGalaxies: json['Number of Galaxies'],
      totalMass: json['Total Mass (Solar Masses)'],
      distanceFromEarth: json['Distance from Earth (million light years)'],
      notableMemberGalaxies: json['Notable Member Galaxies'],
      discoveryYear: json['Discovery Year'],
    );
  }
}
