///***Supabase Table Defintion***
///
///```sql
/// create table
///  public."Interstellar_Clouds" (
///    "Cloud Name" text null,
///    "Type" text null,
///    "Size (light years)" text null,
///    "Distance from Earth (light years)" text null,
///    "Discovery Year" text null,
///    "Interesting Facts" text null,
///    id bigint generated by default as identity not null,
///    constraint Interstellar_Clouds_pkey primary key (id),
///    constraint Interstellar_Clouds_id_key unique (id)
///  ) tablespace pg_default;
///  ```
class InterstellarCloud {
  final int? id;
  final String? cloudName;
  final String? type;
  final String? size;
  final String? distanceFromEarth;
  final String? discoveryYear;
  final String? interestingFacts;

  InterstellarCloud({
    this.id,
    this.cloudName,
    this.type,
    this.size,
    this.distanceFromEarth,
    this.discoveryYear,
    this.interestingFacts,
  });

  factory InterstellarCloud.fromJson(Map<String, dynamic> json) {
    return InterstellarCloud(
      id: json['id'],
      cloudName: json['Cloud Name'],
      type: json['Type'],
      size: json['Size (light years)'],
      distanceFromEarth: json['Distance from Earth (light years)'],
      discoveryYear: json['Discovery Year'],
      interestingFacts: json['Interesting Facts'],
    );
  }
}
